# Generated by Django 4.0.1 on 2022-01-11 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alien',
            old_name='given_name',
            new_name='given_name_of_subject',
        ),
    ]
